### ISSUE TITLE
Where is the source or container images?

### ISSUE THREAD

**Issue by nnasaki** [yoshioterada/k8s-Azure-Container-Service-AKS--on-Azure#2]
I could not try [3.0 Prepare Dockerfile (Multi-Stage Build)](https://github.com/yoshioterada/k8s-Azure-Container-Service-AKS--on-Azure/blob/master/Kubernetes-Workshop3.md#30-prepare-dockerfile-multi-stage-build) . I could not build docker images. Because, I could not find source codes.

Where is the source codes or container images?

**Comment by yoshioterada** [comment]
Dear Masaki-san.

Please create thd Dockerfile on the same directory with Maven project directory?
In my Maven project, look like follows.

```
$ ls
Dockerfile			hazelcast-default.xml		pom.xml
build-create.sh			k8s				src
create-deployment-svc.yaml	nb-configuration.xml		target
create-deployment-svc.yaml-e	policy.yaml
```

Key point is following. copy "src" directory of Maven project to the " /usr/src/myapp/src" directory of container images as well as pom.xml file.

```
COPY src /usr/src/myapp/src
COPY pom.xml /usr/src/myapp
RUN mvn -f /usr/src/myapp/pom.xml clean package
COPY target/payara-micro.jar /usr/src/myapp/payara-micro.jar
```

**Comment by nnasaki** [comment]
Thank you for answer. I understand that. I think that it is more helpful to prepare a sample source this repository or anther repository.

**Comment by yoshioterada** [comment]
Thank you so much for your advise!!
Yes, I will add more information to the explanation and also will include sample codes and script.

To improve the documents, I'm very appreciate your advise.
Thank you & Best Regards.

**Comment by yoshioterada** [comment]
I added the [Sample Java Manven Project](https://github.com/yoshioterada/k8s-Azure-Container-Service-AKS--on-Azure/tree/master/AccountSvc) as well as explanation on [3. Basic operation to create and publish the Service](https://github.com/yoshioterada/k8s-Azure-Container-Service-AKS--on-Azure/blob/master/Kubernetes-Workshop3.md).

I hope this explanation may help.
Please review it ? If I need more explanation, I will consider to write more.

**Comment by nnasaki** [comment]
Alright. Thank you yoshio3. I will check it later.

**Comment by yoshioterada** [comment]
Dear nnasaki-san. Thank you so much for your messages. I will close this issue due to no response from you anymore.
